spring:
  application:
    name: proxy

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://172.31.32.42:3306/borderless?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true